# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Package application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  # Manuelle Auslösung über GitHub UI

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install build

    - name: Install Runtime Requirements (falls benötigt)
      run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build Source Distribution (PEP 517)
      run: |
          python -m build --sdist

    - name: Upload Distribution Artifact
      uses: actions/upload-artifact@v4
      with:
          name: sdist-package
          path: dist/*.tar.gz

    - name: Create GitHub Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          Automated release from commit ${{ github.sha }}
          
          This release contains the packaged Calibre-Web application.
        files: dist/*.tar.gz
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
